version: 2
jobs:
  Build:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_HUB_SECRET" | docker login --username $DOCKER_HUB_LOGIN --password-stdin

      - run: docker build -t jdudmesh/justthetalk-api:$CIRCLE_BUILD_NUM .
      - run: docker push jdudmesh/justthetalk-api:$CIRCLE_BUILD_NUM

  Deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a3:4c:48:b4:c3:6e:9a:12:4c:27:f8:11:be:fd:d0:72"
      - run: |
          echo 'justthetalk.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDjO6cmYwqSA0JRMPXC7I3ufaltngzy5QUcgoQABzyJvj44gbZFCDjTCa/+m8J3dO/U8JAfX+XOTlwTW5R2/WVw=' >> ~/.ssh/known_hosts
      - run: |
          ssh circleci@justthetalk.com /home/circleci/deploy.sh $CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-workflow:
    jobs:
      - Build
      - Deploy:
          requires:
            - Build